#ifndef _PS2_H
#define _PS2_H

#define PS2_COMMAND_SET_LED 0xED
#define PS2_COMMAND_ECHO 0xEE
#define PS2_COMMAND_GETSET_SCAN_CODE_SET 0xF0

#define PS2_DATA_SCROLL_LOCK 0x0
#define PS2_DATA_NUMBER_LOCK 0x1
#define PS2_DATA_CAPS_LOCK 0x2
#define PS2_DATA_GET_SCAN_CODE_SET 0x0
#define PS2_DATA_SET_SCAN_CODE_1 0x01
#define PS2_DATA_SET_SCAN_CODE_2 0x02
#define PS2_DATA_SET_SCAN_CODE_3 0x03

#define PS2_RESPONSE_ACK 0xFA
#define PS2_RESPONSE_RESEND 0xFE
#define PS2_RESPONSE_SCAN_CODE_1 0x43
#define PS2_RESPONSE_SCAN_CODE_2 0x41
#define PS2_RESPONSE_SCAN_CODE_3 0x3F

#endif
