#ifndef _PS2_KEYBOARD_H
#define _PS2_KEYBOARD_H 1

#define PS2_COMMAND_REGISTER 0x64
#define PS2_DATA_PORT 0x60
#define PS2_STATUS_REGISTER 0x64

#define PS2_READ_COMMAND_BYTE 0x20
#define PS2_WRITE_COMMAND_BYTE 0x60
#define PS2_SELF_TEST 0xAA
#define PS2_INTERFACE_1_TEST 0xAB
#define PS2_INTERFACE_2_TEST 0xA9
#define PS2_DISABLE_KEYBOARD 0xAD
#define PS2_ENABLE_KEYBOARD 0xAE
#define PS2_READ_INPUT_PORT 0xC0
#define PS2_READ_OUTPUT_PORT 0xD0
#define PS2_WRITE_OUTPUT_PORT 0xD1
#define PS2_SET_SCANDCODE_SET 0xF0
#define PS2_SYSTEM_RESET 0xFE
#define PS2_DISABLE_MOUSE 0xA7
#define PS2_ENABLE_MOUSE 0xA9
#define PS2_WRITE_MOUSE 0xD4
#define PS2_IDENTIFY 0xF2
#define PS2_DISABLE_SCANNING 0xF5
#define PS2_ENABLE_SCANNING 0xF4
#define PS2_KEYBOARD 1
#define PS2_MOUSE 2
#define PS2_KEYBOARD_KEY_RELEASED 0xF0
#define PS2_KEYBOARD_MULTIMEDIA 0xE0
#define PS2_KEYBOARD_LEFT_ALT_PRESSED 0x11
#define PS2_KEYBOARD_LEFT_ALT_RELEASED 0x11
#define PS2_KEYBOARD_RIGHT_ALT_PRESSED 0x11
#define PS2_KEYBOARD_RIGHT_ALT_RELEASED 0x11
#define PS2_KEYBOARD_LEFT_CONTROL_PRESSED 0x14
#define PS2_KEYBOARD_LEFT_CONTROL_RELEASED 0x14
#define PS2_KEYBOARD_RIGHT_CONTROL_PRESSED 0x14
#define PS2_KEYBOARD_RIGHT_CONTROL_RELEASED 0x14
#define PS2_KEYBOARD_LEFT_SHIFT_PRESSED 0x12
#define PS2_KEYBOARD_LEFT_SHIFT_RELEASED 0x12
#define PS2_KEYBOARD_RIGHT_SHIFT_PRESSED 0x59
#define PS2_KEYBOARD_RIGHT_SHIFT_RELEASED 0x59
#define PS2_ACK 0xFA
#define PS2_RESEND 0xFE


void ps2_keyboard_init();

#endif